### ISSUE TITLE
ST config

### ISSUE THREAD

**Issue by jonkke8** [b4skyx/dotfiles#2]
My st quite literally is barebones, nothing changed after installing your rice using the curl command. Is it somehow linked to zsh or..?
Also polybar looks a bit strange :/ (The font in the images would be nice)
.... And rofi icons are very small, compared to the images.

![2021-09-07-150944_1920x1080_scrot](https://user-images.githubusercontent.com/45978346/132342186-2d6df90c-cb04-4786-9dd2-c97a4d012149.png)

**Comment by b4skyx** [comment]
For st, make sure you have xresources patch applied. I make use of the xresources to configure st.
Polybar seems to have font issues. What are your contents of the `.fonts` directory? You need waffle font for the icons.
Rofi icons should be fine, if you use a 1920x1080 resolution screen. If you're using more, just change the font size in the config. Let me know if that's the case, i'll point you where to make changes.

**Comment by jonkke8** [comment]
## Ok, I got the font working.

## This is what I mean by small icons.
![2021-09-09-182534_1920x1080_scrot](https://user-images.githubusercontent.com/45978346/132715358-f1e778e0-7c63-470c-beae-5f763706058f.png)

## And finally, I'm still not sure how to patch the xresources.
[also could I make the polybar's network thingie have more bars, looks strange with only 2 bars. (I'm on ethernet by the way)]

**Comment by jonkke8** [comment]
![2021-09-09-191931_1920x1080_scrot](https://user-images.githubusercontent.com/45978346/132724055-04c43e51-f76c-4b6d-b34d-1e84db823921.png)

### I assume this is not how it's supposed to look like, I tried adding the patch somehow. Most likely wasn't right lol
#### Everytime I try to run a command, it says "'#bfddb2': unknown terminal type."

**Comment by b4skyx** [comment]
You can try [this fork](https://github.com/siduck76/st) for st. It has the patch and other things you might need included. Mine is a minimal patch since I use tmux, so it may not fit your needs.
Alternatively you can write colors directly via ansii sequence codes if you wish to not patch for some reason.

As for the icons in rofi, try modifying [this line](https://github.com/b4skyx/dotfiles/blob/d7e868caed091e32b5c6e6d9a7b189d03ea75fd0/.config/rofi/iconic.rasi#L76) in rofi iconic config. Make it from 48 to 64.

**Comment by jonkke8** [comment]
Alright I'll try. I will update this comment if anything is either successful or a huge failure

Edit 1; Installing the fork of st did work, although I don't notice a difference from Alacritty at all lol

Edit 2; I had already tried to change the icon size before, no matter what I change it to, it wont change.

### Additional questions;
- How do I open the rofi powermenu?
- Why am I getting a trillion errors when trying to use nvim?

**Comment by b4skyx** [comment]
ST has low memory usage, faster launch time. It all boils down to personal preference and performance. I find st fast enough to make it my default. 

Icon size not changing is weird. Are you having the Flatery icon pack? Your icons might have missing 48px or 64px artifacts. Try changing the icon-theme to some larger pack like papirus and see if that works. 

- For rofi-powermenu, you would need a custom script. There is a [logout.sh](https://github.com/b4skyx/unix-scripts/blob/main/scripts/logout.sh) but I don't have custom icons in it yet. I just use keybinds to logout. Since I have a laptop I have a button to power off as well.

- Run PlugInstall after you use nvim. That should fetch the required plugins. If you could log or screenshot what errors you get, that would be helpful.

**Comment by jonkke8** [comment]
Thanks. For the nvim part, I did PlugInstall, but even after that it still gave me a bunch of .lua errors.

**Comment by b4skyx** [comment]
Can you detail what errors you got?

**Comment by jonkke8** [comment]
![errors](https://user-images.githubusercontent.com/45978346/132801618-289532cd-85fb-4dbf-a57c-921914174963.png)
 Maybe even hundreds more after those

I checked the path for the init.lua's, not one plugin had it.

**Comment by jonkke8** [comment]
And also after installing Papirus for example, the icon size doesn't change in the slightest.

**Comment by b4skyx** [comment]
Perhaps vim wasn't cloned well. [Here](https://github.com/b4skyx/conf-nvim) is the config. You can clone it manually.
As for the icon size, I ain't sure what's wrong. The rofi config does changes the icon size for me.

**Comment by jonkke8** [comment]
> Perhaps vim wasn't cloned well. [Here](https://github.com/b4skyx/conf-nvim) is the config. You can clone it manually.

This worked after downloading from that repo.

Rofi on the other hand, I can live with it. The icon size has been a bug(?) from when I started using bspwm.

Edit...
Now there's text on the bottom of nvim saying;
"```use_internal_diff is not deprecated, please use diff_opts.internal```"

Editerer
How do I change the icon theme again? I remember it being forced by some config file, I don't remember which though.

**Comment by b4skyx** [comment]
Remove [this](https://github.com/b4skyx/conf-nvim/blob/4fc10159ae3a0908eedbff12553392c1c42812e8/lua/conf-gitsigns/init.lua#L37) line. Incase you do use luajit, you can set `diff_ops.internal = true` instead.
