### ISSUE TITLE
Conky and other features + PR for zsh?

### ISSUE THREAD

**Issue by Spuxy** [b4skyx/dotfiles#6]
##### Hey @b4skyx . In older branch gruvbox was there any purpose of system_all.conf at conky dir ?

* Btw. would be good for ur scripts to add them into path ? to run them globally instead of run them with full path ?

* Btw. if im trying to run rofi-emoji it screams that "frece" command could not be found  👎🏿 ?

* Btw. do u think u could please hint me how to migrate ur old configuration of gruvbox into new rofi configuration ? Im kinda confused with some argb or what is that 😭

* Btw. what would u do to make this repo more "dynamic" for monitors settings for bspwm and poly? -> i would like to do smth like export MAIN = $(xrandr --query | grep 'XY') and put this variable into rofi/bspwm ? Im not good with bash could u please hint me ? or may i contact u on discord?

##### I can PR for zsh structure to make it easier, u can check that 💯

**Comment by b4skyx** [comment]
Ah system_all.conf in the gruvbox is yet another conky theme I like. It showed the overall system usage 

As for the scripts, yes you can add them to the path. It is intended to be used like that only.

Frece is a cli database written in rust. I use it to store frequecy of the rofi emojis. You need to install it in order to get rofi-emoji script 

You can refer to the documentation of rofi and note down the parameters discontinued. Just replace them with the newer syntax. 

I do use multiple monitors. I check if my secondary monitor is connected using xrandr. If yes, spawn a second desktop there using bspc. You can refer to my polybar startup script and bspwmrc for how to do that. It's working in the main branch.

**Comment by Spuxy** [comment]
@b4skyx 

Idk if im bothering u but 

```
bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
        if [ "$(xrandr -q | grep -w 'connected' | wc -l)" -eq "3" ]; then
          bspc monitor HDMI-1 -d 1 2 3 4
          bspc monitor DP-1 -d 5 6 7 8 9
        elif [ "$(xrandr -q | grep -w 'connected' | wc -l)" -eq "2" ]; then
          bspc monitor HDMI-1 -d 1 2 3 4 5
          bspc monitor eDP-1 -d 6 7 8 9
        elif [ "$(xrandr -q | grep -w 'connected' | wc -l)" -eq "1" ]; then
          bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
        fi
        ;;
      *)
      ;;
  esac
done &
```
or u can use similiar script to detect monitors without reloading + into if statements u need to put xrandr script
